# -*- coding: utf-8 -*-
# v5 content model: 32 Perry/Ignite-only units, six tiers, typed by AI dependency.
# Source: Ignite Mastermind Material/00 - The Skill Parsing 2026-09-12.md
# Counts: 15 AI-centric, 10 AI-assisted, 7 not about AI.

TIERS = [
 {"id":"t0","short":"Diagnostics","n":"Tier 0","name":"Diagnostics","c":"var(--cyan)","hex":"#3CC2DB",
  "tag":"Four readings taken in front of you, in under a week each",
  "promise":"Four measurements about how machines currently see you, what your funnel is really doing, and what your AI spend produces. Nothing installed, nothing to maintain.",
  "lede":"This tier is the strongest part of the material it comes from, because that material is not a course. It is eighteen months of live office hours where people brought problems to a screen and had them diagnosed in public. What survives is the diagnostic move rather than the framework around it. Each of these produces one number or one answer, and two of them take under an hour.",
  "why":[
    {"h":"The model's answer beats your opinion of your positioning","p":"Ask an answer engine who you are and what you are known for. Whatever comes back is the measurement. It is free, it takes a minute, and it ends the conversation about whether the positioning is working."},
    {"h":"A reading is not a proposal","p":"Every one of these hands you something about your own operation. None of them requires us to know your business first, which is why they are the only things on this site that can go first."},
    {"h":"Two of the four are about money, not models","p":"The funnel read and the spend-to-output read have no AI in them. They are here because the material teaches them in AI sessions and they decide whether any of the AI work is worth starting."}],
  "how":"We measure in front of you rather than going away and returning with a deck. The visibility check runs logged out, because a signed-in account personalises its own answers and will tell you what you want to hear."},

 {"id":"t1","short":"Ground truth","n":"Tier 1","name":"Ground truth","c":"var(--navy)","hex":"#222639",
  "tag":"Measurement and routing, before anything gets built on top",
  "promise":"Know what your tracking actually captures, what each model costs you, and where your knowledge base gets its information, before any of it carries weight.",
  "lede":"Three engagements that everything above depends on. The source material is explicit that an ad with zero purchases can still be alive if the upstream steps are moving, which you cannot see without the tracking. It is equally explicit that routing work across models without a benchmark is guesswork with a subscription attached.",
  "why":[
    {"h":"Bad signal trains the platform against you","p":"Bot traffic generating fake conversions is not a reporting problem. The algorithm learns from it and starts finding more bots. Conversion tracking stopped being measurement and became defence."},
    {"h":"Cost is a routing input, not an afterthought","p":"The rule the material arrives at is quality over price, but measurable quality over price. The second clause is what makes it a rule rather than a slogan, and it requires a benchmark."},
    {"h":"A knowledge base is only as good as what went in","p":"Vet the sources or do not build the thing. Naming trusted sources converts finding good documentation from a judgement call into a retrieval task."}],
  "how":"Events close to the money first, because actions harder for a bot to fake carry more signal. Then a benchmark the routing agent re-reads rather than a model list somebody memorised."},

 {"id":"t2","short":"Working relationship","n":"Tier 2","name":"The working relationship","c":"var(--red)","hex":"#EE2A52",
  "tag":"How one person sets up with one model, before any agent exists",
  "promise":"The setup that makes everything above it work: instructions the model actually has, memory that survives the session, and a protocol for the day the model changes underneath you.",
  "lede":"This is the tier with no equivalent anywhere else in our catalogue, and it exists because the source material shows the same failure over and over. People fail at agent work for reasons that have nothing to do with agents. No memory file. No guardrails. No preparation. Six engagements that fix the layer underneath.",
  "why":[
    {"h":"Preparation, not prompts","p":"The single most repeated line in eighteen months of sessions: successful AI automation does not begin with prompts, it begins with preparation. Skill, research, guardrails, context. Then prompt."},
    {"h":"The model does not read its own changelog","p":"A new release does not make your existing setup better. Somebody has to ask it to review what you built with the new capabilities in mind, and almost nobody does."},
    {"h":"The ladder became a fork and that matters","p":"Chat, then Cowork, then Code was taught as a progression in January. By July the middle step had become a destination for a whole class of user. Routing somebody up when they should go sideways wastes months."}],
  "how":"Interview rather than instruct. The strongest single technique in the corpus is handing the model a list of questions and having it ask them one at a time until it says it is clear."},

 {"id":"t3","short":"Agent build","n":"Tier 3","name":"Agent and system build","c":"var(--gold)","hex":"#F1B900",
  "tag":"The largest tier, and the part of the source nobody else has",
  "promise":"Specialised agents with one job each, a second brain they read from, and the architecture for running them without the bill scaling with the work.",
  "lede":"Seven engagements, and this is where the source material is genuinely scarce rather than merely useful. Almost all of it is a practitioner working on a shared screen rather than teaching, which means what you get is the decisions and not the pitch: why the coding environment is deliberately separate from the orchestrator, why a second vendor reviews rather than produces, why maintenance is scheduled rather than triggered.",
  "why":[
    {"h":"One responsibility each, and the fence is the point","p":"The agent template ends with a clause people skip: you are not doing other work, this is the only thing you do. Without the fence the specialists drift back into being one generalist."},
    {"h":"The same shape survives the domain change","p":"Two independent rosters exist in the source, one organised by software discipline and one by marketing deliverable. Every member changes and the orchestrator-plus-specialists shape does not, which is what proves it is architecture rather than habit."},
    {"h":"Cost is structural, not incidental","p":"Each agent carrying only its own context is a cost argument before it is an organisational one. That is why the porting pattern names token management alongside security."}],
  "how":"Model it where iteration is cheap, confirm it works, then port with security and token cost as the constraints. Schedule the maintenance rather than waiting for something to break."},

 {"id":"t4","short":"Production","n":"Tier 4","name":"Production and distribution","c":"var(--purple)","hex":"#8F5ED8",
  "tag":"Getting the work in front of people, and being findable when they look",
  "promise":"Creative that platforms read as genuinely different, a production pipeline with a measured cost, and a positioning that answer engines can repeat back.",
  "lede":"Six engagements covering the reach half. Half of them are AI-assisted rather than AI systems, and the two that are neither are here because the source teaches them inside AI sessions: email infrastructure and the warm-up schedule that decides whether any of it arrives.",
  "why":[
    {"h":"The platform decides what counts as different","p":"Changing a headline or a background colour is read as the same creative. Six genuinely distinct concepts is not a style preference, it is the minimum the ranking system will recognise."},
    {"h":"Citation is the new ranking","p":"Falling traffic is often low-intent traffic now answered in the overview, and it was never going to convert. Brand mentions across the web, rather than backlinks, are what gets a business named."},
    {"h":"Deliverability is upstream of everything","p":"Five hundred on day one, five hundred on day two, dedicated subdomains from the start. It is the least interesting engagement on this page and it decides whether the rest of the channel exists."}],
  "how":"Reporting in the order the customer experiences the funnel, so drop-off is visible and a campaign with zero purchases can be read as alive rather than dead."},

 {"id":"t5","short":"Commercial","n":"Tier 5","name":"Commercial practice","c":"var(--teal)","hex":"#1F7A8C",
  "tag":"Six engagements, and five of them have no model in them anywhere",
  "promise":"How a practice that installs AI systems gets clients, prices the work, and builds an offer that survives the tooling being replaced.",
  "lede":"This tier is the finding. It comes out of what everyone calls the AI curriculum, and almost none of it is about AI. It is classic direct response: pricing, outreach, positioning, and an argument against the recurring revenue that the rest of the industry treats as settled. We publish it typed rather than quietly folded in, because the label is the useful part.",
  "why":[
    {"h":"The source contains both sides of the retainer argument","p":"One engagement sells a maintenance retainer derived from an observed decay property. Another argues directly against monthly billing and says to let the client ask. Four days apart, from the same practice, unreconciled. We hold both and say which fits you."},
    {"h":"It is the half that cannot rot","p":"Every AI-centric engagement on this site names a model that will be wrong within a year. Nothing in this tier carries a version number."},
    {"h":"The buyer is different","p":"Do not read this tier as an extension of the five above it. These sell to somebody running a practice, not somebody running a marketing function."}],
  "how":"Price to what the client recovers rather than to what it costs us, and never to what a naive buyer would pay. The stated reason is retention: a client who finds out later what the market rate was does not stay."},
]

U = {}

def u(slug, **k): U[slug] = k

# ---------------- TIER 0 : Diagnostics ----------------
u("ai-visibility-check", t="t0", type="A", name="The AI Visibility Check", time="1 hour",
  who="Founder, whoever owns the brand",
  promise="What the answer engines say when somebody asks who you are, taken live and logged out.",
  problem="You have a positioning statement. Nobody has checked whether the systems that now answer most questions about your category have ever heard it.",
  cost="A positioning nobody outside the building shares is not a positioning. Businesses spend years being known for something the market has never associated with them, and the first signal usually arrives as a lost deal nobody can explain.",
  hard="Almost nothing, technically, and that is the point. What people get wrong is running it signed in. A personalised account returns answers shaped by your own history, which is how an operator concludes his clients rank first everywhere when they do not.",
  work=[
    "Two queries, run logged out and in a clean session: who is [your name] and what are they known for, and the same for the company.",
    "The same queries across more than one engine, because they disagree and the disagreement is informative.",
    "A competitive pass: the three queries a buyer in your category would actually type, and who gets named instead of you.",
    "Where the answers came from. The cited sources are the properties actually doing the work, and they are rarely the ones you have been maintaining."],
  get=["The verbatim answers, with their sources, across engines",
       "The gap between what you say you are known for and what comes back",
       "The list of properties currently speaking for you",
       "Three queries you are absent from that you should not be"],
  money="An hour, and the cheapest thing on this site. It exists to make the next decision obvious rather than to become a project.",
  gate="**If the answer comes back empty, that is a finding and not a failure.** Some categories return no clear leader at all, which makes them cheap to win and changes what we would recommend next.")

u("presence-authority-audit", t="t0", type="A", name="Digital Presence and Authority Audit", time="3 days",
  who="Founder, CMO",
  promise="An inventory of the proof you already have, and what is currently visible of it.",
  problem="The assumption is that authority needs to be built. Usually it exists and is not placed anywhere a machine or a buyer can find it.",
  cost="Proof that lives in your head, in old decks and in private client results is proof that does no work. Meanwhile the effort goes into producing new material, which is the expensive way to solve a distribution problem.",
  hard="Separating proof from credentials. Results, experience, worked cases and lessons learned all count; a title does not. People consistently inventory the wrong column and conclude they have nothing.",
  work=[
    "Search your own name and the company's, and record what a stranger actually finds in the first screen.",
    "Inventory the proof that already exists: results, worked examples, stories, things that went wrong and were fixed.",
    "Identify the three topics you can credibly own for a year, as themes rather than as content ideas.",
    "Map each proof point to where it is currently published, which is usually nowhere."],
  get=["A written positioning statement: who you help, what you help them do, the result",
       "The proof inventory, with each item's current visibility",
       "Three content anchors for the next twelve months",
       "The publishing gap, item by item"],
  money="Three days. It pairs with the Visibility Check and we would rather sell them together than either alone.",
  gate="**This produces a position, not traffic.** If you need volume rather than clarity, Tier 4 is the correct starting point and we will say so.")

u("funnel-shaped-report", t="t0", type="A", name="The Funnel-Shaped Reporting Read", time="2 days",
  who="Head of growth, media buyer, whoever gets asked why the number moved",
  promise="Your ad reporting rebuilt in the order the customer experiences it, and the drop-off read out loud.",
  problem="Reporting is a scorecard. It says what happened and not where. Campaigns get killed on the final number while the steps before it were moving.",
  cost="An ad with zero purchases and healthy upstream steps gets switched off, and the budget moves to something worse. The reverse is more expensive: clicks that never reach the page get read as a creative problem and creative gets rebuilt, when the fault was page speed or tracking.",
  hard="Nothing, once somebody has done it. The column order is the entire technique, and it is invisible until you see the two views side by side.",
  work=[
    "Build the custom column preset in the platform, ordered left to right as the customer moves: reach, click, landing page view, content view, add to cart, checkout, purchase.",
    "Read the drop-off between each pair of steps rather than the end number.",
    "Apply the two diagnostic rules: upstream movement with no purchases means alive, not dead; clicks that never reach the page mean speed or tracking, not creative.",
    "Hand over the setup, because the view is per-account and cannot be shared."],
  get=["The preset, built in your account",
       "A written read of where your funnel actually loses people",
       "The two diagnostic rules, applied to your live campaigns",
       "A cheat sheet so each person on the team can rebuild the view"],
  money="Two days, and it is a skill transfer rather than a report. You should not need us to read it again.",
  gate="**This needs an account with enough volume for the steps to be legible.** Below a few hundred conversions the drop-off pattern is noise and we will tell you that rather than reading tea leaves.")

u("spend-to-output-audit", t="t0", type="A", name="The AI Spend-to-Output Audit", time="3 days",
  who="COO, finance, whoever approves the subscriptions",
  promise="What your AI spend produces, stated as output rather than as cost.",
  problem="The question in the room is how much the tooling costs. That question has an easy answer and it is the wrong one, so the decision that follows is usually to trim.",
  cost="Trimming an AI budget on cost alone removes the seats producing the most and keeps the ones producing nothing, because cost per seat is uniform and output per seat is not. The saving is real and the loss is invisible.",
  hard="Getting a before figure that anyone believes. Most teams have no baseline, and reconstructing one after the fact is where this work actually goes.",
  work=[
    "Inventory every AI subscription, seat and API line, with who holds it.",
    "For each holder, establish an output measure in their own units: assets, drafts, tickets, builds, reels.",
    "Reconstruct a before figure where one exists, and mark it as reconstructed where it does not.",
    "Rank by output per pound, and name the seats that produce nothing."],
  get=["A per-seat output table, with the before figure marked as measured or reconstructed",
       "The seats producing nothing, named",
       "One reallocation recommendation with the arithmetic attached",
       "A measure you can re-run next quarter"],
  money="Three days. It is the engagement most likely to pay for the rest of the page and the one least likely to be asked for.",
  gate="**We will not use somebody else's benchmark as your before figure.** The source material's own example is a single unverified case with a vague baseline, and we are not repeating it as evidence.")

# ---------------- TIER 1 : Ground truth ----------------
u("conversion-tracking-install", t="t1", type="N", name="Conversion Tracking Install", time="1 week",
  who="Media buyer, developer, whoever owns the site",
  promise="Server-side conversion tracking with events chosen close to the money, and a bot filter that does not punish real buyers.",
  problem="Browser pixels observe what a browser does, and a bot can do most of it. Fake activity with realistic names and addresses is now common enough to move the algorithm.",
  cost="This is the failure that compounds against you. The platform learns from whatever you send it, so bot-generated conversions teach it to find more bots. You do not get a flat result, you get a worsening one, and the reporting looks fine throughout.",
  hard="Choosing the events. Everything downstream depends on picking actions that are hard to fake and close to a real transaction, and the temptation is always to instrument the easy ones.",
  work=[
    "Audit what the current pixel is actually firing, and how much of it could be automated.",
    "Select events by proximity to money rather than by convenience, on the stated principle that the closer an event is to a financial transaction the more valuable its signal.",
    "Build the Conversions API integration server-side, with deduplication against the existing pixel.",
    "Install the honeypot: a hidden form field invisible to humans, with two automation paths depending on whether it was filled. This replaces CAPTCHA, which modern models answer easily and which costs you genuine prospects.",
    "Verify with live traffic and compare the two signal sources for a fortnight."],
  get=["Server-side tracking, live and deduplicated",
       "An event map ordered by proximity to revenue",
       "The honeypot field, installed, with both automation paths built",
       "A fortnight of side-by-side signal comparison"],
  money="One week. There is no AI in this engagement at any point, which is why it is the cheapest thing here to keep working.",
  gate="**If your site is on a platform that will not accept server-side events, we will say so before starting** rather than building half of it.")

u("model-routing-cost-read", t="t1", type="C", name="Model Routing and Cost Read", time="1 week",
  who="Whoever holds the AI budget and the technical lead",
  promise="A routing rule for which model does which job, held against a live benchmark rather than against what was true when you set it up.",
  problem="Work gets sent to whichever model somebody trusts. Usually that is the most expensive one, for everything, including work that does not need it.",
  cost="Routing by habit is expensive in both directions. You overpay on the bulk of the work and underperform on the part that actually needed the stronger model, and because the bill is a single line nobody can see either half.",
  hard="The tiebreaker. The rule that makes this work is quality over price, but measurable quality over price, and the second clause requires you to have decided what measurement means for each job type before the routing exists.",
  work=[
    "Classify your recurring AI work by job type: writing, documentation, code, orchestration, research, image, video.",
    "Set the subscription-first ordering, so the capacity you already pay for is used before anything is bought by the token.",
    "Build the routing agent, given a live benchmark and instructed to re-read it before each job class rather than holding a memorised list.",
    "Install the recurring check, because the model list changes weekly and a routing table written today is wrong within the quarter.",
    "Write the sensitivity rule: which categories of data never leave which vendor. In the source material this rule lives in the operator's head, and that is the part we fix."],
  get=["A routing table by job type, with the reasoning",
       "The routing agent, reading a live benchmark",
       "A scheduled re-check, with an owner",
       "A written data-sensitivity boundary, in the file rather than in somebody's head"],
  money="One week to build, and it is the engagement on this site most likely to pay for itself inside a quarter.",
  gate="**This ages faster than anything else we sell.** The scheduled re-check is not an upsell, it is the reason the engagement is worth buying, and we will not build it without one.")

u("source-vetting", t="t1", type="A", name="Source Vetting for a Knowledge Base", time="3 days",
  who="Whoever will own the knowledge base",
  promise="A named, defensible source list, so building the knowledge base stops being a judgement call.",
  problem="Find good documentation is an instruction nobody can follow. The result is whatever the model surfaced that day, permanently embedded in everything the system later says.",
  cost="Bad sources do not announce themselves once they are inside a retrieval system. They come back later as confident answers, and by then nobody remembers where a given claim entered.",
  hard="Being specific enough. The technique that works is naming individual sources by name, which feels arbitrary and is the entire point: it converts retrieval from a judgement into a task.",
  work=[
    "Decide what the knowledge base is for, in one sentence, because it determines what counts as a good source.",
    "Name the sources: official documentation, change logs, and the specific individuals whose work you actually trust, by name.",
    "Set the exclusion rule and write it down, since information from an invalid source is feeding the thing you will later rely on.",
    "Establish the refresh schedule, so the list is re-examined rather than inherited."],
  get=["A named source list, with the reason each one is on it",
       "A written exclusion rule",
       "The refresh schedule, with an owner",
       "A first ingestion pass run against the list"],
  money="Three days, and it is a precondition for the second brain rather than an alternative to it.",
  gate="**This is not a research engagement.** We are fixing where your information comes from, not producing the information.")

# ---------------- TIER 2 : The working relationship ----------------
u("claude-ecosystem-fork", t="t2", type="C", name="The Ecosystem Fork", time="2 days",
  who="Anyone about to commit a team to a way of working",
  promise="Which environment each person on your team should actually be in, and why it is not the same one.",
  problem="The advice in circulation is a ladder: start in chat, move to the collaborative tool, graduate to the coding environment. It was taught that way and it stopped being true within six months.",
  cost="Routing somebody up the ladder when they should go sideways costs months. A person who wants AI working with their information and processes does not need a coding environment, and putting them in one produces a confident conclusion that AI is not for them.",
  hard="Nothing technical. The difficulty is that the ladder is a more satisfying story than the fork, so it survives past the point where it describes anything.",
  work=[
    "Classify the work each person actually does, against the three environments.",
    "Route by the shape of the work rather than by seniority or technical confidence.",
    "Name explicitly who should stop climbing, because the collaborative environment is a destination for a whole class of user rather than a waypoint.",
    "Set the assets question: where the outputs live once produced, which is the part every version of this advice omits."],
  get=["A per-person routing, with the reasoning stated",
       "The list of people who should not move up",
       "A decision about where produced assets live",
       "A re-check trigger, since this changed inside six months once already"],
  money="Two days. It is the cheapest engagement in this tier and it decides how expensive the others are.",
  gate="**We will name people who should not be using these tools at all.** If that is not a conclusion the engagement can reach, it is not worth running.")

u("new-model-protocol", t="t2", type="C", name="The New-Model Release Protocol", time="2 days",
  who="Technical lead, whoever gets asked whether to upgrade",
  promise="A standing procedure for what happens when the model underneath you changes, so the answer is not improvisation.",
  problem="A release lands and either nothing happens or everything is torn up. Neither is a decision, and both are common.",
  cost="Launch day is the worst time to evaluate anything. Server load, usage restrictions and early rushes make the model look worse than it is, and the conclusions drawn in the first twenty-four hours persist for months.",
  hard="Believing the central claim, which sounds wrong: the model does not automatically know how to use its own improvements. Your existing instructions were written for the previous one and will quietly under-use the new one until somebody asks it to review them.",
  work=[
    "Install the wait. Twenty-four hours, no exceptions, for the rush and the restrictions to settle.",
    "Update, set effort to the highest setting, and do not start anything from scratch.",
    "Run the re-evaluation: have the model review your existing skills, connectors, agents and prompts against its own change log, and report what it can now do better.",
    "Add the cost clause, which is what turns a capability review into a budget review in one sentence.",
    "Write the whole thing down as a standing procedure with an owner, because the value is in it firing every time."],
  get=["The protocol, written, with an owner and a trigger",
       "The re-evaluation prompt, ready to run",
       "A first pass run against your current setup",
       "A record of what the review changed, so the next one is comparable"],
  money="Two days to install. It runs itself afterwards, which is the point.",
  gate="**This is the lightweight version.** If you are running more than a handful of skills and agents, the eight-step migration is the correct engagement and this one will under-serve you.")

u("model-migration", t="t2", type="C", name="The Eight-Step Model Migration", time="2 weeks",
  who="Technical lead on a system with real surface area",
  promise="A full migration across agents, skills, connectors and vendor files, in an order that does not overwrite your own work.",
  problem="A large setup does not migrate by updating a version number. Agents, skills, MCP connections, prompts and supporting files all encode assumptions about the model they were written against.",
  cost="The specific expensive mistake is ordering. Update your prompts first and the newer vendor files land on top of them, so the work is done twice and the second time nobody is sure what was lost.",
  hard="Step four, and it is the reason to buy this rather than improvise it: vendor files before prompts. That constraint was discovered by being burned, not derived, and it is not obvious in either direction until it has cost you.",
  work=[
    "Give the agent the current documentation for the new model, rather than describing it.",
    "Create the model-selection framework first, so routing exists before anything is rewritten.",
    "Audit the estate: agents, skills, MCP connections, prompts, supporting files, with counts.",
    "Update vendor files, then rewrite prompts. Never the other way.",
    "Add the recurring checks, test against a real task rather than a self-report, correct the model when it claims success it has not verified, then run the final prompting sweep."],
  get=["The migrated estate, with a before-and-after inventory",
       "A model-selection framework, written",
       "Scheduled re-checks with owners",
       "A real-task test result, not a self-report"],
  money="Two weeks for a system of any size. The source ran it against more than a hundred skills.",
  gate="**Step seven includes a standing rule we will install whether you ask or not:** the agent may not claim something is complete unless it has verified the result. If that rule is unwelcome, this is the wrong supplier.")

u("preparation-before-prompts", t="t2", type="C", name="Preparation Before Prompts", time="1 week",
  who="Anyone whose AI work keeps failing in ways nobody can reproduce",
  promise="The four things that have to exist before a prompt is worth writing, installed.",
  problem="Complex work gets handed to a model cold, with a well-crafted instruction and nothing else. It half-works, unpredictably, and the response is to improve the prompt.",
  cost="Prompt refinement against a preparation problem is the most expensive loop in this whole field, because it is nearly free to stay in. Teams spend quarters improving instructions against a ceiling instructions cannot move.",
  hard="Accepting that the prompt is the last step rather than the first. Everything upstream of it is unglamorous: a dedicated skill, research into the target system, guardrails, and enough context for the model to make a judgement rather than a guess.",
  work=[
    "Create the dedicated skill for the task, rather than describing the task in a prompt.",
    "Research the target platform and put what you find where the model can read it.",
    "Add the guardrails: what it must not do, and what it must confirm before proceeding.",
    "Supply the context needed to decide, not just to execute.",
    "Install the improvement loop, because a skill that never changes after a successful run is wasting the run."],
  get=["A working skill for your highest-value repeated task",
       "The guardrail set, written",
       "A context pack the model actually reads",
       "The improvement loop, with a trigger"],
  money="One week. It is the engagement most likely to make an existing failing setup start working without replacing anything.",
  gate="**We will tell you where the prompt stops mattering.** For agentic work with tools and a browser, the practitioner this comes from says plainly there was no secret sauce in his prompt, and we are not going to sell you prompt craft into that case.")

u("instructions-interview", t="t2", type="C", name="The Global-Instructions Interview", time="2 days",
  who="Every individual using the tool, one at a time",
  promise="A complete instruction file per person, produced by interview rather than by template.",
  problem="Global instructions get written once, from a blank page, by somebody guessing at what matters. They are generic, and being generic is the one thing they cannot afford to be.",
  cost="A weak instruction file is not neutral. It is re-read at the start of every session, so every vague line is a small tax paid thousands of times, and nobody attributes the resulting friction to it.",
  hard="Nothing, once you know the move. Hand the model the questions and make it ask them one at a time, waiting for each answer, then write the file. The version where somebody answers all five at once produces a visibly worse file.",
  work=[
    "Run the five-question interview per person: role and what they do, how they want to be spoken to and which behaviours annoy them, three things never to do, three non-negotiable safety rules, spelling and always-on context.",
    "Have the model write the complete file in one block, then review it against what was actually said.",
    "Extend it for the heavier users with the thirty-question version, which loops until the model states it is clear.",
    "Install it, and set a review trigger."],
  get=["A complete instruction file per person",
       "The interview transcript, so the file can be re-derived",
       "The thirty-question extension for heavy users",
       "A review trigger"],
  money="Two days for a team. It is the highest ratio of benefit to effort anywhere on this site.",
  gate="**It has to be one question at a time.** If the process gets compressed to save an afternoon, the output is a template and you should not pay us for a template.")

u("memory-persistence", t="t2", type="C", name="Memory and Context Persistence", time="2 days",
  who="Anyone who has re-explained their project to a model more than twice",
  promise="A memory file the model reads first, every session, without being asked.",
  problem="The single most common complaint in eighteen months of live sessions is losing context between conversations. People re-explain the same project weekly.",
  cost="Re-establishing context is not just the time it takes. The model works from whatever the person remembered to mention this time, so the quality of the work varies with the quality of the re-explanation, and nobody can see that happening.",
  hard="The initiation, not the file. Writing a memory file is easy. Making it the first thing read on every new conversation is the part people skip, and without it the file is a document nobody opens.",
  work=[
    "Create the memory file and decide what belongs in it, which is state rather than instruction.",
    "Wire the project instruction file to check it at the start of every conversation.",
    "Set the update discipline: what gets written back, when, and by whom.",
    "Test across a session boundary, with a real task, rather than asking the model whether it worked."],
  get=["The memory file, populated",
       "The initiation wiring, tested across a session boundary",
       "A write-back discipline",
       "A convention that survives more than one project"],
  money="Two days. Pairs with the instructions interview and we would rather do both at once.",
  gate="**Memory is state, not instructions.** If what you actually need is for the model to behave differently, that is the interview engagement above and this one will not fix it.")

# ---------------- TIER 3 : Agent and system build ----------------
u("subagent-install", t="t3", type="C", name="The Specialised-Subagent Install", time="3 weeks",
  who="Technical lead, COO",
  promise="An orchestrator and a set of specialists with one job each, scoped so they stay in their lane.",
  problem="One assistant is asked to do everything. It holds the whole project in context, costs accordingly, and is mediocre at each individual thing because it is optimised for none of them.",
  cost="A generalist agent is expensive twice: the context bill scales with the whole project rather than with the task, and the output quality sits at the average of everything it is trying to be.",
  hard="The scope fence. The template ends with a clause people drop because it sounds redundant: you are not doing other work, this is the only thing you do. Without it the specialists converge back into one generalist within weeks and nobody notices the drift.",
  work=[
    "Decide the roster by your own work rather than by ours. Two independent rosters exist in the source, one by software discipline and one by marketing deliverable, and the fact that both work is the evidence that the shape is portable.",
    "Write each agent with its activation condition, its permitted tools and connections, and its scope fence.",
    "Set up the orchestrator as project manager, holding the plan rather than the work.",
    "Give each specialist only the context its own job requires, which is the cost argument as much as the organisational one.",
    "Test by giving the orchestrator a real task end to end."],
  get=["An orchestrator plus a specialist roster, built for your work",
       "Each agent scoped, with its activation condition written",
       "A context boundary per agent",
       "An end-to-end run on a real task"],
  money="Three weeks. The largest engagement in this tier and the one the rest assume.",
  gate="**Autonomous-agent patterns can get an account suspended.** The source material records that happening. We will design within the vendor's terms and tell you where that limits what you wanted.")

u("skill-authoring", t="t3", type="C", name="Skill Authoring and the Improvement Loop", time="2 weeks",
  who="Whoever will own the skills after we leave",
  promise="Skills as the shipped unit, with a loop that makes each successful run improve the next one.",
  problem="Capability lives in prompts people keep in documents, in their heads, or in a chat history. It cannot be versioned, handed over, or improved deliberately.",
  cost="Undocumented capability leaves with the person. More quietly, a skill that never changes after a successful run throws away the only free information you get, which is what worked.",
  hard="The loop, not the authoring. Writing a skill file is straightforward. Establishing that every successful run is an opportunity to improve the next one requires a trigger and an owner, or it does not happen.",
  work=[
    "Identify the repeated work worth turning into skills, in order of frequency.",
    "Author each as a skill file with its activation condition, scope and tools.",
    "Install the improvement loop with an explicit trigger, on the stated principle that skills should never remain static.",
    "Set the review cadence against vendor changes, since skills written for one model under-use the next.",
    "Hand over with a standard, so the next skill somebody writes looks like these."],
  get=["A skill set for your highest-frequency work",
       "An authoring standard the team can follow",
       "The improvement loop, with a trigger and an owner",
       "A review cadence tied to vendor releases"],
  money="Two weeks. This is the engagement that determines whether anything else in this tier survives our leaving.",
  gate="**We will not author skills for work you have not yet done manually.** A skill written before the task is understood encodes a guess, permanently.")

u("second-brain-build", t="t3", type="C", name="The Second Brain Build", time="3 weeks",
  who="Chief of staff, ops, whoever keeps asking where something is",
  promise="A vetted, indexed knowledge base your agents read from, with a schedule that keeps it current.",
  problem="Information is spread across tools, documents and browser bookmarks. Retrieval is a person remembering, which means it does not scale and does not survive that person being away.",
  cost="A knowledge base built from whatever was to hand is worse than none, because it is trusted. Once a bad source is inside a retrieval system its claims come back as answers and nobody can trace where they entered.",
  hard="The vetting, which is Tier 1 work and cannot be skipped, and the maintenance, which is where every version of this project dies. The fix in the source is a weekly scheduled job rather than an intention.",
  work=[
    "Run the source vetting first, or do not start.",
    "Build the vault and the index, then connect the agent environment to it.",
    "Ingest against the named source list: official documentation, change logs, and the individuals you named.",
    "Install the recurring update job so new material arrives on a schedule rather than when somebody remembers.",
    "Install the recovery move, because these structures do get away from people, and the fix is asking the system to reorganise itself and walk you through it."],
  get=["A working second brain, connected to your agent environment",
       "An index built from a named source list",
       "A weekly update job, with an owner",
       "A written recovery procedure"],
  money="Three weeks, and the source vetting is a separate prerequisite rather than part of it.",
  gate="**This is the engagement clients most often want without the vetting.** We will decline that combination rather than build something whose answers cannot be traced.")

u("browser-automation", t="t3", type="C", name="Browser Automation Install", time="2 weeks",
  who="Ops lead, whoever owns a platform with no usable API",
  promise="An agent that drives a logged-in browser through work that has no API, built as a reusable skill.",
  problem="The most repetitive work in a marketing operation sits inside vendor interfaces that expose no automation. People do it by hand because there is no other option.",
  cost="Hand-operated platform work is the largest recoverable cost in most small operations and the least visible, because it is spread across everybody's week in half-hour pieces.",
  hard="Not the prompt. The practitioner this comes from, asked what he typed, said there was no secret sauce in his prompt. The difficulty is preparation and guardrails: what the agent may touch, what it must confirm, and what happens when the interface moves.",
  work=[
    "Pick the target workflow by frequency and by how mechanical it is.",
    "Create the skill and let the agent research the target platform before it touches anything.",
    "Set the guardrails: which account, which actions, what requires confirmation, what is never permitted.",
    "Run it live against real work with somebody watching, then iterate. Delays and troubleshooting are the normal shape of this, not a sign it is failing.",
    "Alternatively record the workflow being done by hand and convert the recording into the skill, which is now the faster route for well-defined tasks."],
  get=["A working browser skill for one real workflow",
       "A guardrail set, written",
       "A live supervised run",
       "The pattern documented so the second workflow is cheaper"],
  money="Two weeks for the first workflow. The second and third are substantially less.",
  gate="**Interfaces move and this breaks when they do.** We will say which parts are brittle and build the check that tells you it broke, rather than letting you find out from a customer.")

u("voice-chat-agent", t="t3", type="C", name="Voice and Chat Agent Deployment", time="2 weeks",
  who="Whoever answers the phone, and whoever wishes they did not",
  promise="A voice or chat agent that books appointments and answers from a knowledge base, configured the way that actually performs.",
  problem="These get deployed with a weak prompt and an overloaded knowledge base, and then judged on the results.",
  cost="The specific failure repeated across the source material: the agent sounds generic, does not book anything, and the business concludes voice AI does not work. In every diagnosed case the prompt was wrong and appointment booking had never been enabled.",
  hard="The knowledge base decision, which is not obvious and is where most of the performance sits. Content in the prompt is faster. Content in the FAQ function is a separate call on every single question. And a knowledge base split across many documents performs worse than one consolidated document.",
  work=[
    "Write the prompt properly, rather than starting from the default.",
    "Make the knowledge-base call deliberately: what goes in the prompt for speed, what goes in the knowledge base, and consolidate to one document.",
    "Enable appointment booking as a named action. It is a selection, not something you ask for in the prompt.",
    "Add custom actions where an external knowledge source is genuinely needed, via an MCP connection.",
    "Test against real calls, and hand over with the prompt documented so the client can change it."],
  get=["A deployed voice or chat agent, booking appointments",
       "A consolidated knowledge base",
       "Custom actions where required",
       "The prompt, documented and editable by you"],
  money="Two weeks. The platform capability is usually already inside a subscription you hold.",
  gate="**We hand over after a testing period and we do not monitor it indefinitely.** The source practice is explicit about that boundary and we would rather state it than discover it.")

u("port-architecture", t="t3", type="C", name="Prototype and Port Architecture", time="3 weeks",
  who="Technical lead running agents at cost",
  promise="Agents modelled where iteration is cheap, then ported to where running them is cheap, with security and token cost as the constraints.",
  problem="Agents get built where they will run, so every iteration costs production money, and the first architecture is the one you are stuck with.",
  cost="Building in the expensive environment makes experimentation expensive, so less of it happens, so the design is worse. The cost shows up as a bill and the real loss is the iterations nobody ran.",
  hard="The porting constraints, in order. Security first, token management first, and only then equivalence of output. Most ports are attempted in the reverse order and get abandoned when the bill or the exposure surfaces.",
  work=[
    "Model the agent where iteration is cheapest and confirm it does what you want.",
    "Port with security as the leading constraint, deciding what the runtime may reach.",
    "Then token management: what runs on subscription capacity, what runs on a local model, and where quality genuinely requires the expensive route.",
    "Verify equivalence on real tasks rather than on a self-report.",
    "Document both halves, because the prototype is now the specification."],
  get=["The agent running in the target runtime",
       "A security boundary, written",
       "A token-cost comparison across routes",
       "An equivalence test on real tasks"],
  money="Three weeks. Worth it where the agent runs often; not worth it where it runs weekly.",
  gate="**We will name where a cheaper local model does not hold quality.** The source assumes it can and offers no measurement, and we are not going to inherit that assumption on your behalf.")

u("vibe-coded-build", t="t3", type="C", name="Vibe-Coded Application Build", time="2 weeks",
  who="Founder with a tool-shaped idea and no development team",
  promise="A working internal tool or client-facing app, specified properly and built where the credits go furthest.",
  problem="The build platforms are good enough now that the constraint is the specification, not the coding. Most attempts fail at the brief.",
  cost="Building straight into the most expensive platform from a vague description is how a fortnight of credits becomes a prototype nobody wants. The first build is what costs, and it costs most when the spec was thin.",
  hard="The spec, and the platform choice. The technique the source arrives at is to have one model produce a complete, structured specification, then hand that to the build platform. Choosing the platform on cost rather than on reputation is the second half.",
  work=[
    "Turn the idea into a structured specification: objective, users, screens, data, constraints, and what done means.",
    "Choose the build environment on cost and output quality for your case rather than by default.",
    "Build the first working version, then move it to a hosting environment if the build tool is not where it should live.",
    "Handle domain, payments and access properly, which is where most of these stall.",
    "Hand over with the specification, since that is the durable artifact."],
  get=["A working application",
       "The specification, which outlives the platform",
       "Domain, hosting and access configured",
       "A cost comparison for the next build"],
  money="Two weeks for a first version. Ambition is the variable, not the timeline.",
  gate="**We will tell you when the answer is an existing product.** A meaningful share of what people want built here already exists inside a subscription they hold.")

# ---------------- TIER 4 : Production and distribution ----------------
u("creative-concept-set", t="t4", type="A", name="The Creative Concept Set", time="2 weeks",
  who="Head of growth, creative lead",
  promise="Six genuinely distinct creative concepts, built so the platform reads them as different rather than as variants.",
  problem="Testing produces variations: a new headline, a different background, another cut. The account fills up and the learning rate does not move.",
  cost="The platform recognises a swapped headline or a recoloured background as the same creative, so a test budget spread across variants buys you one result at the price of twenty. The account looks busy and learns nothing.",
  hard="Separating a message from its dressing, which a team inside the account cannot reliably do about its own work. The distinction has to come from outside or it does not come.",
  work=[
    "Audit what is actually in the account: how many distinct messages sit behind the asset count.",
    "Build against the six concepts as six different conversations rather than six formats: problem-unaware, harsh truth, testimonial, founder story, comparison, benefit-driven.",
    "Map each concept to a stage of customer awareness, so the set covers the journey rather than clustering.",
    "Produce a first wave, one per concept, and measure the spread rather than the winner.",
    "Hand over the classification method, since this has to run continuously."],
  get=["A message count for your existing account",
       "Six concepts, mapped to awareness stages",
       "A first production wave, one per concept",
       "The classification method, transferred"],
  money="Two weeks. It assumes an account with enough spend for a spread to mean something.",
  gate="**This is not a creative production retainer.** We build the set and the method; producing at volume against it is Tier 3 work or your own team's.")

u("video-image-pipeline", t="t4", type="C", name="AI Video and Image Pipeline", time="3 weeks",
  who="Content lead, whoever is quoted for production",
  promise="A generation pipeline with the model choice routed by task and the cost per asset measured rather than assumed.",
  problem="Generative production gets done ad hoc, in whichever tool somebody likes, with no measurement of what an asset actually costs.",
  cost="Without routing you pay premium rates for work that did not need them, and without measurement you cannot tell whether the pipeline is cheaper than what it replaced. Most teams believe it is and cannot show it.",
  hard="The routing and the measurement, not the generation. Generation is the easy part now. Knowing which model to send a given job to, and what the resulting asset cost, is the work.",
  work=[
    "Classify your asset types and route each to a model on quality and cost together.",
    "Build the pipeline for the highest-volume type first, end to end, including the unglamorous steps.",
    "Measure cost per finished asset, against whatever it replaced.",
    "Set the review cadence, because this is the fastest-moving part of the field and a routing choice made today is wrong within a quarter.",
    "Document the prompts and settings as artifacts rather than leaving them in a chat history."],
  get=["A working pipeline for your highest-volume asset type",
       "A routing table with cost per asset",
       "A measured comparison against the prior method",
       "Prompts and settings, documented"],
  money="Three weeks. The one engagement here with a measured cost figure behind it in the source, and it is a single unverified case.",
  gate="**Every model named in this engagement will be wrong within a year.** The review cadence is not optional and we will not build the pipeline without it.")

u("repurposing-engine", t="t4", type="A", name="The Repurposing Engine", time="2 weeks",
  who="Content lead, founder who is the face of the brand",
  promise="One recording that becomes many assets, with the conversion automated rather than assigned to somebody.",
  problem="Long-form content gets made and published once. The clips, quotes, posts and summaries that should come out of it require a person, so they do not happen.",
  cost="The recording is the expensive part and it is already paid for. Everything not repurposed is production cost already spent and never recovered, and it is also the material that would have given answer engines reason to cite you.",
  hard="Keeping the pipeline from producing obvious slop. The automation is available; the judgement about what is worth cutting is what makes the output usable, and it has to be encoded rather than assumed.",
  work=[
    "Choose the recurring long-form format and the topics your audience actually asks about.",
    "Build the capture setup so recording, streaming and archiving happen in one pass.",
    "Automate the conversion into short assets, with a selection step rather than a blanket cut.",
    "Set the publishing cadence and the destinations.",
    "Connect it back to the visibility work, since a growing library is what gets a business named."],
  get=["A capture setup that records, streams and archives in one pass",
       "An automated conversion pipeline with a selection step",
       "A publishing cadence",
       "A library structure that compounds"],
  money="Two weeks. The setup is the engagement; the running is yours.",
  gate="**If you are not already producing long-form, this is the wrong engagement.** It multiplies an input and cannot create one.")

u("organic-visibility", t="t4", type="A", name="The Organic Visibility Program", time="2 weeks + monthly",
  who="Founder, CMO",
  promise="A position stated clearly enough that both people and machines repeat it back the same way.",
  problem="Most operators wear several hats and communicate all of them at once. The result is accurate and unusable: nothing to be known for.",
  cost="Scattered signals do not average out into a general reputation. They produce no reputation, and the systems now answering questions about your category have nothing to work with, so they name somebody else.",
  hard="Choosing. The framework is four steps and three of them are easy. Deciding the one outcome your name should attach to, and accepting what that excludes, is the whole engagement.",
  work=[
    "Identity clarity: one positioning statement covering who you help, what you help them do, and the result.",
    "Presence audit, using the Tier 0 visibility check as the measurement rather than an opinion.",
    "Authority signals: inventory what you already have, on the principle that authority does not require a title.",
    "Content anchors: three topics for the year, as themes rather than as ideas.",
    "Monthly: publish against the anchors and re-run the visibility measurement."],
  get=["A positioning statement, decided",
       "A measured before-and-after on the visibility check",
       "Three content anchors for twelve months",
       "A monthly re-measurement"],
  money="Two weeks to set, then monthly. The monthly part is measurement and publishing discipline, not content production.",
  gate="**We will tell you what to stop being known for.** If every hat has to stay on, the engagement cannot do its job and we would rather not start it.")

u("answer-engine-position", t="t4", type="A", name="Answer Engine Positioning", time="2 weeks + monthly",
  who="CMO, SEO owner, whoever is explaining the traffic chart",
  promise="A read on why your traffic moved, and a position built for being cited rather than clicked.",
  problem="Organic traffic falls and it gets treated as an SEO failure. Often it is not: the informational queries are now answered directly, and that traffic was never going to convert.",
  cost="Responding to an overview-driven traffic drop with more keyword content is expensive and makes it worse. You spend against the exact queries the engine has stopped sending anywhere.",
  hard="Changing what gets counted. Citation is the new ranking and branded search is the new moat, which means the reporting has to change before the strategy can, and the old numbers will look worse under the new measure before they look better.",
  work=[
    "Separate the traffic that left from the traffic that converted, and establish how much overlap there ever was.",
    "Build the citation measure: where you are named across engines for the queries that matter, taken logged out.",
    "Structure the properties so they can be cited: answer-first, question in the heading, structure a machine can parse.",
    "Shift the measure to brand mentions across the web rather than backlink counts.",
    "Monthly: re-measure, and report citation rather than sessions."],
  get=["A diagnosis of what your traffic drop actually was",
       "A citation baseline across engines",
       "Structural changes to the properties that carry your answers",
       "A monthly citation report replacing the sessions report"],
  money="Two weeks to baseline, then monthly. **The monthly is the measurement, and we sell it as compliance rather than as a promised position.**",
  gate="**We will not promise a citation position.** These systems are nondeterministic, the same query returns different answers hours apart, and anyone selling you a guaranteed placement is selling you a number nobody controls.")

u("email-infrastructure", t="t4", type="N", name="Email Infrastructure and Warm-Up", time="1 week",
  who="Whoever owns the sending domain",
  promise="A sending setup that arrives, warmed on a schedule, with messaging compliance prepared before you apply for it.",
  problem="A new domain or IP gets used at volume immediately. Deliverability collapses quietly and the campaign is judged on the results.",
  cost="Reputation damage on a sending domain is slow to acquire and slower to undo. The messages that vanish are invisible, so the conclusion is usually that the list is cold or the copy is weak.",
  hard="Patience, and the preparation nobody does. Approval for messaging registration starts before you submit: forms, consent boxes, live policy pages and no conflicting widgets. Submitting first and fixing after is how weeks disappear.",
  work=[
    "Set up dedicated sending subdomains from the start, rather than sending from the primary.",
    "Run the warm-up: five hundred on day one, five hundred on day two, gradual increases every few days as reputation establishes.",
    "Prepare the messaging registration before submitting: separate promotional and service consent checkboxes, live Terms and Privacy pages linked inside the forms, no conflicting chat widget on a form page.",
    "Test deliverability across the major providers before scaling.",
    "Document the schedule so the next domain does not start from zero knowledge."],
  get=["Dedicated subdomains, configured",
       "A warm-up schedule, running",
       "A registration application prepared before submission",
       "A deliverability test across major providers"],
  money="One week of setup and several weeks of patience. No AI at any point.",
  gate="**We will not accelerate the warm-up because a launch date moved.** The schedule is the engagement.")

# ---------------- TIER 5 : Commercial practice ----------------
u("maintenance-retainer", t="t5", type="A", name="The Maintenance Retainer", time="Ongoing",
  who="You, if you sell AI systems. Your client, if you buy them",
  promise="A recurring service built on the fact that AI systems decay, priced against an observed property rather than a pricing tactic.",
  problem="AI systems are sold as builds. Models change, APIs change, vendor instructions change, skills go stale, and six months later the thing works worse than it did at handover.",
  cost="For the buyer, a system that quietly degrades is worse than one that fails, because nobody investigates. For the seller, a one-time build means the relationship ends exactly when the decay starts and the client's experience of your work is its worst version.",
  hard="Nothing to build. The difficulty is that this is usually invented as a pricing strategy and therefore sold unconvincingly. Derived from the decay instead, it is a genuine need and sounds like one.",
  work=[
    "Monitor vendor documentation and change logs on a schedule.",
    "Update agents, skills and vendor files when the model underneath changes, in the correct order.",
    "Test performance against real tasks rather than self-reports.",
    "Resolve compatibility issues as vendors move.",
    "Report what changed and what it cost, so the retainer is auditable rather than assumed."],
  get=["Scheduled monitoring, with an owner",
       "Updates applied in the correct order",
       "Real-task performance testing",
       "A change report each period"],
  money="Ongoing. **The most directly transferable commercial idea in the source material**, and the only one derived from an observed property rather than asserted.",
  gate="**Read this against the engagement below it, which argues the opposite.** The same practice sells this retainer and argues against monthly billing four days apart. We hold both positions and will tell you which fits your buyer rather than pretending there is one answer.")

u("pricing-architecture", t="t5", type="N", name="Pricing Architecture", time="1 week",
  who="Founder, whoever writes the proposals",
  promise="Three pricing methods, matched to the three situations they each work in, with an explicit rule against extraction.",
  problem="Pricing is set by instinct and defended by anecdote. The same service goes out at wildly different numbers depending on how the conversation went.",
  cost="Underpricing is the obvious loss. Overpricing a buyer who does not know the market is the expensive one: they find out, they leave, and they tell people. The source is blunt that a client who discovers they were taken will resent it permanently.",
  hard="Knowing which method applies. Markup works for tooling-based services, value-based works where the client's recovery is measurable, time-based is the fallback for low volume. Applying the wrong one produces a number you cannot defend in the room.",
  work=[
    "Establish hard cost per service, including tooling and delivery time.",
    "Apply the markup method where the service is tooling-based: ten to twenty times hard cost plus implementation.",
    "Apply value-based pricing where recovery is measurable: count the missed calls, the lost leads, the unbilled hours, and price against the recovered amount.",
    "Use time-based as the fallback for clients with too little volume for either.",
    "Install the anti-extraction rule: price where nobody can undercut you, because retaining a client costs less than acquiring one."],
  get=["A rate structure with three methods and the trigger for each",
       "Hard cost per service, calculated",
       "A value-based worksheet for the measurable cases",
       "The anti-extraction rule, written into the process"],
  money="One week. No AI in it anywhere, and it will not need revisiting when the models change.",
  gate="**We will argue against your highest defensible price.** The rule here is deliberately not revenue-maximising in the short term, and if that is not what you want, this is the wrong engagement.")

u("one-off-first", t="t5", type="N", name="The One-Off-First Sequence", time="1 week",
  who="Founder, sales lead",
  promise="A sales sequence that opens with a single transaction and lets the recurring relationship be asked for rather than proposed.",
  problem="Every piece of advice in the market says to sell recurring revenue first. Buyers are increasingly tired of being billed monthly, and the ask is large at the exact moment trust is smallest.",
  cost="Leading with a retainer maximises the size of the first decision. Most prospects decline it and would have said yes to something smaller, so the pipeline reads as poor fit when it is actually poor sequencing.",
  hard="Holding the line when the one-off closes well. The instinct is to convert immediately. The sequence works because the client asks, and asking too early resets it.",
  work=[
    "Design the one-off: small, complete, genuinely useful on its own, and not a trojan horse.",
    "Price it to be an easy yes and deliver it visibly better than expected.",
    "Do not propose the ongoing. Let the second conversation start from the client's side.",
    "Build the ownership variant for buyers who want to own an agent for a flat fee rather than subscribe to one.",
    "Track which clients ask, and how long it takes, so the sequence is measured rather than believed."],
  get=["A one-off offer, specified and priced",
       "A delivery standard for it",
       "The ownership-model variant",
       "A tracking measure on ask rate and time to ask"],
  money="One week to design. It changes the shape of the pipeline rather than the volume.",
  gate="**This contradicts the maintenance retainer above and we are not going to hide that.** Both come from the same practice, four days apart. Which one fits depends on whether your buyer experiences your work as a system that decays or as a project that completes.")

u("results-in-advance", t="t5", type="N", name="Results-in-Advance Outreach", time="2 weeks",
  who="Founder, whoever does business development",
  promise="An outreach sequence that leads with work already done rather than with a request for a meeting.",
  problem="Cold outreach asks for time before it has given anything. Response rates reflect that, and the response is usually to send more of it.",
  cost="Volume outreach with nothing in advance burns the list and the sender's name at once. You get a low response rate and a reputation, and both are hard to reverse.",
  hard="Doing the work before the yes. Every part of this is easy except the part where you produce something real for somebody who has not agreed to anything, which is precisely why so few do it.",
  work=[
    "Identify a narrow target set where the same improvement is visible from outside.",
    "Do the work first: the rebuild, the audit, the fix, actually produced.",
    "Send something physical that gets opened, with the work attached.",
    "Let them name the price on the first transaction, so the first exchange is not a negotiation.",
    "Offer the obvious adjacent service at the point of delivery, since the relationship is now established."],
  get=["A target set and the repeatable improvement for it",
       "A physical send that gets opened",
       "A first-transaction structure with the price left open",
       "A measured response rate on your own sends"],
  money="Two weeks to build the sequence. The per-send cost is real and is the reason the targeting has to be narrow.",
  gate="**The outcome numbers in the source are one practitioner's self-report on an unstated sample.** Seventy-five per cent response and a seven-hundred-and-fifty average are what he said, not what we measured, and we will not quote them to you as evidence.")

u("single-lane-positioning", t="t5", type="N", name="Positioning for a Single Lane", time="1 week",
  who="Founder deciding what the next five years say",
  promise="One thing to be known for, chosen on evidence rather than on preference.",
  problem="Generalists are not being rewarded. Being credible at several things reads as being the leading name in none of them, and the systems answering buyers' questions reflect that exactly.",
  cost="A diluted position is not a smaller version of a strong one. It returns nothing. The practitioner this comes from does not appear in his own category's leader list despite running its first conference for five years, because his signal is spread across everything else he has done.",
  hard="The evidence half. Deciding what you want is easy; establishing which fields have no clear leader, and are therefore cheap to enter, requires actually running the queries.",
  work=[
    "Run the leader queries across your candidate fields and record which return no clear answer at all.",
    "Score each candidate on three axes: what you want to be known for, how crowded it is, and whether you would enjoy five more years of it.",
    "Choose, and write down what the choice excludes.",
    "Where secondary ventures matter, decide whether they run under a separate identity rather than diluting the primary.",
    "Set the measurement, which is the Tier 0 visibility check re-run quarterly."],
  get=["A scored comparison of your candidate positions",
       "The uncontested fields, named",
       "A decision, with its exclusions written down",
       "A quarterly re-measurement"],
  money="One week. The decision is yours and the evidence is what we are selling.",
  gate="**Fields behave like early search: whoever is at the top tends to stay.** If your chosen field already has an established leader, we will say that the work is harder and more expensive rather than selling you the same engagement at the same price.")

u("ownership-offer", t="t5", type="N", name="The Ownership Offer", time="2 weeks",
  who="Founder designing what to sell next",
  promise="An offer built around the client owning the system rather than renting it, and the service business that sits on top.",
  problem="Everything is sold as a subscription because the industry decided that was the model. Buyer preference has moved and most offers have not.",
  cost="Selling only a subscription loses every buyer who wants to own the thing, and that is now a significant share. It also caps you at the software margin when the durable revenue is in being the person who runs it.",
  hard="Separating what should be owned from what should be ongoing. The system can be owned; the maintenance cannot be, because the decay is continuous. Getting that line wrong produces either an unsustainable promise or an offer nobody wants.",
  work=[
    "Define the ownable unit: what the client buys once and holds.",
    "Price it against the flat-fee alternative rather than against a subscription's lifetime value.",
    "Define the service layer that sits on top, which is where the durable revenue is.",
    "Build the hundred-small-clients version of the model as the alternative to a few large ones.",
    "Write the handover so ownership means something rather than being a licence in different words."],
  get=["An ownable unit, defined and priced",
       "A service layer on top of it",
       "A handover standard that makes ownership real",
       "A model comparison against your current structure"],
  money="Two weeks. It is an offer design engagement, not an implementation.",
  gate="**This rests on a prediction rather than a measurement.** The claim that buyers are moving back to ownership is one practitioner's reading of his own market, and we will present it as that rather than as a trend.")
